### ISSUE TITLE
Migration plan retry successfully completes, number of VM's successful doesn't update to reflect

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/miq_v2v_ui_plugin#420] opened 2018-06-19 15:54 UTC
When a migration plan has a failure, upon a successful retry the number of VM's successfully migrated doesn't update properly.  See attached.

![screenshot from 2018-06-19 10-49-47](https://user-images.githubusercontent.com/4692674/41608806-fb70bb12-73ae-11e8-861c-8f5d40f84e64.png)

**Comment by priley86** [comment] 2018-06-20 17:19
I have not seen this locally - could be related to G release code @AparnaKarve @AllenBW ? 

I think our upcoming issues around the dev environment and API testing will help w/ this sort of bug.

**Comment by AllenBW** [comment] 2018-06-20 17:34
Locally all my plans fail 😏 so can't say I've seen it, @bthurber that url something accessible from the vpn? 's no so much workin for me 🤔

**Comment by bthurber** [comment] 2018-06-20 17:40
@AllenBW yes works on internal VPN.  Just logged in.

**Comment by AllenBW** [comment] 2018-06-20 17:57
In there now, looks to be an older version of v2v :-/

**Comment by vconzola** [comment] 2018-06-21 20:22
@bthurber UI dev team has been unable to reproduce this. Please verify with latest Master and G builds.

**Comment by bthurber** [comment] 2018-06-27 03:46
Confirmed this still exists in latest MiQ nightly build date of 6/25.  
- Timer works beautifully 
- Migration details page updates correctly 
- Migration  over page doesn't update 
- On success retry still have 0 of 2 VMs successfully migrated
![screenshot from 2018-06-26 22-45-40](https://user-images.githubusercontent.com/4692674/41951869-b241201e-7992-11e8-9339-42a872c1ea38.png)

**Comment by priley86** [comment] 2018-06-27 12:34
Can't exactly reproduce this w/o your database, but inspecting your environment, it seems that the plan's id is not matching the request's `source_id` (humble guess w/o a debugger). 

If you can provide a database export, we can take a look...

**Comment by bthurber** [comment] 2018-06-27 12:49
@priley86 you can access my appliance here:  https://miqnightly65.v2v.bos.redhat.com/
Standard creds.  Feel free to export anything you need there.  
Thanks!

**Comment by priley86** [comment] 2018-06-27 13:37
yep - this ended up being enough (I can view the source now). The issue is - our current logic is not projecting the most recent status (and is instead using the existing status). I think I can get a quick fix for this... will cc: @AparnaKarve

**Closed** 2018-06-27 15:39 UTC
Labels: Sprint 10, bug
