### ISSUE TITLE
Networks appear twice

### ISSUE THREAD

**Issue by mperezco** [ManageIQ/miq_v2v_ui_plugin#281] opened 2018-05-02 08:08 UTC
In CloudForms nightly build 2018-05-01, when creating an infrastructure mapping, RHV networks appear twice.
This may be a regression.

**Comment by priley86** [comment] 2018-05-02 14:36
@mperezco this is indeed a regression. I will cherry-pick the commit from sprint6 into `alpha` today and hopefully tomorrow's build fixes this.

**Comment by priley86** [comment] 2018-05-02 15:29
appears this may also be duplicated by #257 - screenshots would help ;)

**Comment by mperezco** [comment] 2018-05-02 22:05
![image](https://user-images.githubusercontent.com/1738510/39551542-afd69190-4e65-11e8-996f-7f7dc6ff31c0.png)

**Comment by bthurber** [comment] 2018-05-24 03:55
Verified I am having this issue in the latest nightly as well.  We should be filtering the target networks the same as we are doing for the source.

**Comment by serenamarie125** [comment] 2018-06-01 13:42
@bthurber we are not able to reproduce in our dev environments.  Is this a priority for sprint 9?

**Comment by serenamarie125** [comment] 2018-06-01 13:42
@AparnaKarve is going to look into getting their database to reproduce the issue locally

**Comment by AparnaKarve** [comment] 2018-06-07 18:01
@agrare A while back we had addressed deduplicating Source Networks in the UI. 
Back then, none of our test environments had duplicates for Target Networks.
But lately, we are seeing a few cases where the Target Networks are also duplicated.

Before we consider making changes in the UI for deduplicating Target Networks, is this something that can be fixed from the backend side?

Based on how we deduplicate the Source Networks, @michaelkro and I discussed how it could be done for Target Networks. While it is doable, I think the UI logic is getting overly complex here.
Hence wanted to double-check if we (UI) could get some relief if the backend handled it for us.
Thanks.

**Comment by AparnaKarve** [comment] 2018-06-07 23:11
@vconzola  We were discussing earlier how the dedupe task in the Mapping Wizard Network Step is different than what @priley86 is working on here https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/395.

The difference is, the Network Step dedupes the display + does the actual mapping
whereas in @priley86 's case we just need to dedupe the display.

The mapping that happens today is many-one as shown below -
```
VM Network (on switch 1)                                                   
                            ------------------>     VM_Tagged (on switch 3)
VM Network (on switch 2)
```

--------------

But now with the duplicate Target Networks in the picture, it will be something like this -

```
VM Network (on switch 1)                                                   
                            ------------------>     VM_Tagged (on switch 3)
VM Network (on switch 2)

VM Network (on switch 1)                                                   
                            ------------------>     VM_Tagged (on switch 4)
VM Network (on switch 2)
```

It would be ideal if the backend handled this type of mapping for us.

**Comment by agrare** [comment] 2018-06-07 23:19
What is the target EMS?  The rules for when two networks with the same name are actually the same or different is not going to be the same depending on the EMS type.  I can help with the VMware rules but we'll need to sync with the ovirt team if the target is RHV.

As for a backend method to do this, we already have a `:lans` so we'd have to add a `:unique_lans` or something which seems hacky.

I'd really like to fix this properly but there would be no way to backport to gaprindashvili.

**Comment by michaelkro** [comment] 2018-06-11 12:09
@AparnaKarve, have run into a bit of a snag.  Due to this [ActiveRecord Validation](https://github.com/ManageIQ/manageiq/blob/master/app/models/transformation_mapping_item.rb#L6), it is actually not possible to create the mappings as described in your [comment above ](https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/281#issuecomment-395594344)

Any idea who I should ask about how these mappings are supposed to work?

**Comment by AparnaKarve** [comment] 2018-06-11 14:20
@michaelkro Good point! I was not aware of this validation at the backend. Thanks.

This brings me back to my original point, that this specific type of mapping/wiring is best handled at the backend possibly by the `TransformationMapping` model itself.

@agrare Sorry to ping you again, but what do you think?
If this can't be implemented at the backend because of portability to G, can the `uniqueness` validation be removed (or adjusted) for `lans`?

**Comment by blomquisg** [comment] 2018-06-11 19:50
I’m not positive if I’m reading two different issues here, or just one.  Here’s what I’m reading:

1) Target networks are displayed multiple times.

2) The mapping model does not support mapping to two separate destinations (targets) at the same time.

For the first issue this might just be something we work through the RHV integration team.  But I’m not sure why it suddenly started happening, or what the level of effort is to fix it.

For the second issue, since the model only supports a single target (correct me if I’m wrong here), the earliest that can change is in the Hammer release (October-ish, 2018).  But that’s not currently on the radar, so if something has to be changed at the model level, let’s get this raised as an RFE in bugzilla for Hammer.

/cc @agrare, @bdunne

**Comment by michaelkro** [comment] 2018-06-11 19:57
@blomquisg
> Target networks are displayed multiple times.

Please correct me if I misspeak @AparnaKarve :)  This occurs when there are two `conversion hosts` on the same provider.  What we see in the UI is something like

1. RHV \ vlan33 (switch_id: 1)
2. RHV \ vlan33 (switch_id: 2)
...

The switch IDs aren't shown in the UI, but can be seen when inspecting the data.  This has actually always been the case, but was missed when originally implementing the UI due to our being unaware of this scenario

**Comment by AparnaKarve** [comment] 2018-06-11 20:23
> This occurs when there are two conversion hosts on the same provider

@michaelkro From @bthurber comment here - https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/257#issue-318692586, it does appear that the Target Network duplication reason is that.

So if that is indeed the case, then could we apply some restrictions (until Hammer is released) that only 1 host can be enabled for the RHV provider with the conversion role?

**Comment by bthurber** [comment] 2018-06-11 20:43
@AparnaKarve I don't think that is desirable....especially if we are migrating hundreds of VM's.  Is there a way to filter duplicates like we do on the source provider?

**Comment by AparnaKarve** [comment] 2018-06-11 20:53
@bthurber Filtering should be possible, and we could display only one instance of the Target Network -- but the above discussion is about the actual mapping between the source and target that will happen under the hood.

Currently, the backend does not let us do this mapping discussed here https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/281#issuecomment-395594344

**Comment by agrare** [comment] 2018-06-21 14:27
Right, are you still doing the logic to dedupe the VMware networks as long as they are in the same datacenter?

**Comment by AparnaKarve** [comment] 2018-06-21 14:29
> are you still doing the logic to dedupe the VMware networks 

Yes, we are. 
The mapping was the only TBD

**Comment by agrare** [comment] 2018-06-21 14:29
LGTM then :+1:

**Comment by AparnaKarve** [comment] 2018-06-21 14:30
Awesome, thanks! :)

**Comment by priley86** [comment] 2018-06-21 18:59
safe to close this issue now @AparnaKarve ?

**Comment by AparnaKarve** [comment] 2018-06-21 19:47
Yes @priley86. Closing it now...

**Closed by AparnaKarve** 2018-06-21 19:47 UTC
Labels: bug
