### ISSUE TITLE
Broken infra mapping button

### ISSUE THREAD

**Issue by Yadnyawalkya** [ManageIQ/miq_v2v_ui_plugin#363] opened 2018-05-31 13:44 UTC
**Description**
`Create Infra Mapping` button seems to be broken, not able to open infra map modal.

![](https://files.gitter.im/ManageIQ/v2v/Jcwh/Screencast-from-2018-05-31-15-08-49.gif)

**Appliance**
upstream/master.20180529235621_bee8c3b

**Comment by AllenBW** [comment] 2018-05-31 14:05
👀

**Comment by michaelkro** [comment] 2018-05-31 14:21
I was originally seeing this exact issue after having followed this sequence this morning
1. Pulled ManageIQ and ManageIQ-Classic master
2. Ran `bin/update` in both repositories

After @AllenBW suggested reinstalling `node_modules`, I completely wiped my local installation, and rebuilt my environment from scratch, and now the issue is resolved.

Is there any way to rebuild the appliance where this issue is being seen?  Perhaps something odd is happening while updating?  @Yadnyawalkya

**Comment by AllenBW** [comment] 2018-05-31 14:21
So I saw this, thought it was an issue, purged and reupped node_modules.. and we're all good...

### a gif of what I seeeeeeeeee (ignore that its a g build, still on v2v master)
![asdfasdf](https://user-images.githubusercontent.com/6640236/40787766-69280ec8-64bc-11e8-9bbc-cb02e088a431.gif)

**Comment by kedark3** [comment] 2018-05-31 17:04
@Yadnyawalkya do we have a BZ for this ?

**Comment by priley86** [comment] 2018-05-31 19:07
@Yadnyawalkya @kedark3 can you confirm that this fixes the issue? I don't see this on my side w/ latest code.

**Comment by kedark3** [comment] 2018-05-31 19:35
Waiting for it to appear in nightly, not in current nightly of 30th May.

**Comment by bthurber** [comment] 2018-06-01 06:03
Verified in latest nightly.

**Comment by priley86** [comment] 2018-06-01 21:05
I would try re-running `bin/update` or `bin/setup` in manageiq. Unfortunately I don't know how to reproduce this here.

**Comment by priley86** [comment] 2018-06-01 21:09
also you can try running `yarn install` in v2v

**Comment by AparnaKarve** [comment] 2018-06-01 23:56
`bin/update` did not resolve this issue on the appliance.

**Comment by AparnaKarve** [comment] 2018-06-02 14:06
So I have narrowed down the issue a little further and have confirmed that this PR in Classic UI - https://github.com/ManageIQ/manageiq-ui-classic/pull/3420 that was recently merged is causing issues with our wizards.

Things to note about this PR -
- This is the very first React PR in the manageiq-ui-classic repo
- It is using `"@manageiq/react-ui-components"`, which is a possible suspect for the issue we are seeing (there could be other problematic packages too, but this one caught my attention)
- It did not fail in Classic UI CI
- It does not cause failures with `bin/update` and webpack compilation
- No failures are seen in the browser console

So what's troubling is, it's pretty much under the radar with no tell-tale signs of something being wrong until we get to the Migration screen and hit the "Create Infrastructure Mapping" button.

@priley86 I think we will just have to examine all the packages being used in this PR and `"@manageiq/react-ui-components"` one-by-one and by the process-of-elimination (which is a long and tedious process) find out what is interfering with our wizards and packages used by the wizards.

I really hope there is a better approach to narrowing this down further.

**Comment by serenamarie125** [comment] 2018-06-02 16:00
yikes!  Thanks for spending so much time on this @AparnaKarve 

@ohadlevy fyi

**Comment by priley86** [comment] 2018-06-02 17:47
@AparnaKarve does pointing `@manageiq/react-ui-components` at the newer version of patternfly-react fix the issue? 

It looks like we have conflicting versions again...`1.16.4`
https://github.com/ManageIQ/react-ui-components/blob/master/package.json#L103

v2v is `2.3.4` 
https://github.com/ManageIQ/miq_v2v_ui_plugin/blob/master/package.json#L67

This is just a hunch. We can start PR'ing updates for PF-R there too but hopefully this does not become a challenge. I think that was the resolution before.

**Comment by mturley** [comment] 2018-06-04 17:13
Any luck with this @michaelkro @AparnaKarve ? Let me know if I can help

**Comment by priley86** [comment] 2018-06-05 12:51
have been discussing this one further w/ @himdel this morning - long term fix seems to be introducing a custom loader for split dependency resolution across plugins... short term fix seems to be upgrading `@manageiq/react-ui-components` to latest pf-react...


cc: @karelhala @AparnaKarve

**Comment by karelhala** [comment] 2018-06-05 12:53
@priley86 PR to update PF to newest version is up https://github.com/ManageIQ/react-ui-components/pull/36

**Closed** 2018-06-07 10:35 UTC
Labels: p1

**Comment by priley86** [comment] 2018-06-11 12:32
@Yadnyawalkya can you confirm it is OK to close this issue now?
