### ISSUE TITLE
All VMs don't show on Migration Plan Request Details Page

### ISSUE THREAD

**Issue by kedark3** [ManageIQ/miq_v2v_ui_plugin#437] opened 2018-06-22 22:30 UTC
See https://bugzilla.redhat.com/show_bug.cgi?id=1594428 for more description

**Comment by priley86** [comment] 2018-06-25 19:19
@AparnaKarve is fixing this in #374 this sprint.

**Comment by AllenBW** [comment] 2018-06-29 14:19
@JPrause a dupe of which bz?

**Comment by JPrause** [comment] 2018-06-29 14:33
@AllenBW see @priley86 comment above.

**Comment by AllenBW** [comment] 2018-06-29 14:39
@JPrause yah, not seeing another bz # 🤷‍♂️

**Comment by JPrause** [comment] 2018-07-03 12:09
Any update on this PR. We have an upcoming build on July 10

**Comment by AparnaKarve** [comment] 2018-07-03 14:44
@JPrause Work is in progress, a PR should be out soon, sometime this week.

**Comment by vconzola** [comment] 2018-07-09 19:24
Duplicate of #374.

**Closed by vconzola** 2018-07-09 19:24 UTC
Labels: duplicate
