### ISSUE TITLE
Migration in progress only shows the size of the first disk

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/miq_v2v_ui_plugin#353] opened 2018-05-25 20:23 UTC
When selecting VMs for migration in a migration plan, Allocated size shows the total size of all disks attached to the source VM.  When running the migration plan, the overview and the migration plan details only lists the size of the first disk for the VM.  It should display the total VM disk size for all disks associated.
![screenshot from 2018-05-23 22-47-50](https://user-images.githubusercontent.com/4692674/40564759-8d4ff220-602f-11e8-9446-10e8f1a655d2.png)

**Comment by mturley** [comment] 2018-06-06 18:55
Starting on this next.

**Comment by mturley** [comment] 2018-06-06 20:06
This one will be another one tough to test-- I can't get any plans to show up as in progress locally. I see where this is in the code though so I'll get fixing it.

But if anyone has a way of seeing that screenshot ^ in a local dev environment (actual or fake migration reporting progress bars) i'm all ears...

**Comment by AllenBW** [comment] 2018-06-06 20:13
OOOOO what about...[ pulling down the summit demo branch](https://github.com/ManageIQ/miq_v2v_ui_plugin/tree/uxd-summit-booth) bringing it up to snuff (locally) n rolling with that?

**Comment by mturley** [comment] 2018-06-06 20:15
Nice idea! I like it. Thanks @AllenBW

**Comment by mturley** [comment] 2018-06-10 21:51
Back from PTO, this is my first order of business tomorrow @vconzola.

**Comment by mturley** [comment] 2018-06-12 01:53
For posterity: I tried rebasing the summit demo branch like Allen said, for getting my mockMode back. We collectively gave up on that (right @AllenBW ?) but he sent me a database that is useful so I will have this issue resolved shortly.

@AparnaKarve, I was told you might know something about this issue, on slack @priley86 said it was some logic he wrote for a demo that you converted. I got a bit distracted today ramping back up (wedding reception hangover = mike starts and ends his day even later than usual) so I haven't figured out the logic issue yet-- reading the code it seems like it should work, to me.

**Comment by AparnaKarve** [comment] 2018-06-14 16:56
The `virtv2v_disks` code that adds up the disk size for all disks looks OK to me, so something else might be amiss here, and it looks like we need a DB from an appliance to be able to fix this.

@bthurber Would you be able to try this test again on the miqnightlynewui VM and let us know when the test is done? Right after your test, I can ssh into the machine and get the database locally that way we will have the DB where we can examine the how the `virtv2v_disks` values appear in the API.
Thanks.

**Comment by mturley** [comment] 2018-06-16 02:34
@AparnaKarve I hope you don't mind being co-assigned here, you can remove yourself if you like. It's helpful for me to see which things have other people looking at them, I don't mean to imply any responsibility when I do that.

**Comment by bthurber** [comment] 2018-06-18 04:59
@AparnaKarve sure thing once we can get e2e working once again.  Should be within the next week.

**Comment by mturley** [comment] 2018-06-18 18:44
Thanks for the update @bthurber . If you could keep me looped in on anything new that'd be great, or if you want @AparnaKarve I can unassign myself if you want this issue to yourself :)

**Comment by AparnaKarve** [comment] 2018-06-20 20:55
@bthurber Thank you for all your testing.

Based on your testing, it looks like this is no longer reproducible - hence closing this issue.

**Closed by AparnaKarve** 2018-06-20 20:55 UTC
Labels: bug, needs-db-support, needs-prioritization, sprint9, testing-in-nightly

**Comment by mturley** [comment] 2018-06-20 20:57
Interesting... I wonder what the problem was. Must have been something on the backend I guess. Thanks for closing this out @AparnaKarve

**Comment by vconzola** [comment] 2018-06-20 21:55
Awesome. Thanks @AparnaKarve.
