### ISSUE TITLE
User can "unschedule" a migration plan

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/miq_v2v_ui_plugin#377] opened 2018-06-01 16:44 UTC

**Comment by blomquisg** [comment] 2018-06-01 21:26
See #369.

API functional requirement:  Allow the caller to specify a migration plan to remove an existing scheduled start time.

**Comment by blomquisg** [comment] 2018-06-04 14:17
If we delete the MIQ Request, also need to dequeue the associated queue message.

**Comment by serenamarie125** [comment] 2018-06-05 16:16
@vconzola please add mockups for unscheduling a migration plan - how do we access that action & what the confirmation would be, as well as noting any notifications which should be produced.

**Comment by AllenBW** [comment] 2018-06-26 14:30
closing, this is kinda a dupe of #369 will be closed by #401

**Closed by AllenBW** 2018-06-26 14:30 UTC
Labels: Sprint 10, needs-api, needs-design, p1
